### ISSUE TITLE
Make site not need PHP on production server

### ISSUE THREAD

**Issue by LizzyTrickster** [LordFokas/MassiveOctoMustache#44]
I think the only place that PHP is used on the production site is for the initial index redirection, if a pure html alternative could be made that would be helpful as I'm moving stuff from one server to another and am going with Nginx for the webserver and don't want to have to fuck about with getting PHP working on there.

My site is gonna be more fun to switch over, yay :/

**Comment by LordFokas** [comment]
we can probably handle it with a .htaccess, when you ask for the root of the website just shamelessly drop a 301 and redirect to the right page.

**Comment by LizzyTrickster** [comment]
Yeah, I'll look into Nginx stuff though
.htaccess is an apache thing, I'll do some testing today and see what I can
come up with

**Comment by LizzyTrickster** [comment]
I <3 Linux symbolic links, just linked `index.html` in the root (server side) to `/miscellaneous/home.html`, so we don't need PHP on the production server at all (for this site, anyway) so I will close this.

@LordFokas the way i pull the site down to the server has also changed so you will need to poke me to update it manually (till I potentially set up another script to do it)

**Comment by LordFokas** [comment]
if you used a symlink, you probably broke every relative link in the site. Also, every link is relative and not absolute, so you broke them all. :p

**Comment by LizzyTrickster** [comment]
How so? When I say symlink, i mean that as far as Nginx is concerned, index.html is just another file. HTTP relative links still work

**Comment by LizzyTrickster** [comment]
Also I think the GitHub IRC notifications are broked again

**Comment by LordFokas** [comment]
because instead of being redirected to the /misc folder you are served a file from the root folder, so relative links point from an outer level than they should.

**Comment by LizzyTrickster** [comment]
You should go to the domain and see for yourself, all the links are
relative to the site's root so everything still works

**Comment by LordFokas** [comment]
doesn't make sense in my head, but it works, so I'll leave it be.
